#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

grid_config()
{
    sudo sed -i '/FeatureType=/c\FeatureType=4' /etc/nvidia/gridd.conf
    sudo sed -i '/EnableUI=/c\EnableUI=FALSE' /etc/nvidia/gridd.conf
}

if [ -n "${DIB_NVGRID_DRIVER_URL:-}" ]; then
    DRIVER_FILENAME=${DIB_NVGRID_DRIVER_URL##*/}
    sudo wget -O /opt/$DRIVER_FILENAME $DIB_DRIVER_URL
    sudo apt install /opt/$DRIVER_FILENAME
    grid_config
elif [ -n "${DIB_NVGRID_DRIVER_FILE:-}" ]; then
    DRIVER_FILENAME=${DIB_NVGRID_DRIVER_FILE##*/}
    sudo apt install /opt/$DRIVER_FILENAME
    grid_config
else
    echo "Either driver url or driver filename must be defined"
    echo "Please set DIB_NVGRID_DRIVER_URL to download driver"
    echo "Please set DIB_NVGRID_DRIVER_FILE to copy driver"
    exit 1
fi
