#!/usr/bin/env python3
import os


def main():
    hosts_override = os.getenv("DIB_HOSTS_ADD", default=None)
    if hosts_override:
        with open("/etc/hosts", "a") as hosts_file:
            for record in hosts_override.split(":"):
                hosts_file.write(record.replace("/", " "))
                hosts_file.write("\n")


if __name__ == "__main__":
    main()

