#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -n "${DIB_NVGRID_HOSTS_FILE:-}" ]; then
    cat $DIB_NVGRID_HOSTS_FILE >> $TMP_MOUNT_PATH/etc/hosts
fi
